$schema: https://docs.renovatebot.com/renovate-schema.json
extends:
  - config:base
regexManagers:
  - fileMatch:
      - ^scripts/run-shfmt$
    matchStrings:
      - 'SHFMT_VERSION="(?<currentValue>.*?)"\\s+#\\s+Current latest version'
    depNameTemplate: mvdan/sh
    datasourceTemplate: github-releases
    versioningTemplate: semver
