name: Prettier Formatting

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm ci

      - name: Run Prettier
        run: ./scripts/run-prettier

      - name: Check for formatting changes
        run: |
          if ! git --no-pager diff --exit-code; then
            echo "::error::Prettier found formatting issues. Please run ./scripts/run-prettier locally and commit the changes."
            exit 1
          fi
