name: Ruff Python Auto-fixes

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  ruff-fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install uv
        shell: bash
        run: |
          pip install --upgrade pip
          pip install uv

      - name: Create venv
        run: |
          uv venv

      - name: Run Ruff auto-fix
        run: |
          ./scripts/run-ruff-fix

      - name: Check for auto-fix changes
        run: |
          if ! git --no-pager diff --exit-code; then
            echo "::error::Ruff found issues that need fixing. Please run ./scripts/run-ruff-fix locally and commit the changes."
            exit 1
          fi
