name: Python Tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    # Add permissions required by the coverage comment action
    permissions:
      # Required for PR comments
      pull-requests: write
      # Required for coverage badge storage
      contents: write
    strategy:
      matrix:
        python-version: ["3.8", "3.x"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        shell: bash
        run: |
          pip install --upgrade pip
          pip install uv

      - name: Create venv
        run: |
          uv venv

      - name: Run tests with coverage
        run: |
          ./scripts/run-coverage

      - name: Coverage comment
        id: coverage_comment
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ github.token }}
          # Only show coverage badge and report for the latest Python version
          SKIP_DEFAULT_BRANCH_COVERAGE: ${{ matrix.python-version != '3.x' }}
