name: Black Python Formatting

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install uv
        shell: bash
        run: |
          pip install --upgrade pip
          pip install uv

      - name: Create venv
        run: |
          uv venv

      - name: Run Black formatter
        run: |
          ./scripts/run-black
          
      - name: Check for formatting changes
        run: |
          if ! git --no-pager diff --exit-code; then
            echo "::error::Black found formatting issues. Please run ./scripts/run-black locally and commit the changes."
            exit 1
          fi