name: Coverage Report

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install uv
        shell: bash
        run: |
          pip install --upgrade pip
          pip install uv

      - name: Create venv and install dependencies
        run: |
          uv venv
          uv pip install -e ".[dev]"

      - name: Run coverage
        run: |
          ./scripts/run-coverage --xml --ci

      - name: Verify coverage files exist
        run: |
          if [ ! -f "./coverage.xml" ]; then
            echo "Error: coverage.xml file not found"
            exit 1
          fi
          if [ ! -f "./pytest.xml" ]; then
            echo "Error: pytest.xml file not found"
            exit 1
          fi
          echo "Coverage files found at expected locations"
          
          # Debug - check file format
          echo "First 30 lines of coverage.xml:"
          head -n 30 coverage.xml

      - name: Python Coverage Comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./coverage.xml
          junitxml-path: ./pytest.xml
          title: Coverage Report
          badge-title: Coverage
          hide-badge: false
          hide-report: false
          create-new-comment: false
          hide-comment: false
          report-only-changed-files: false
          remove-link-from-badge: false
          coverage-path-prefix: /home/runner/work/plex-history-report/plex-history-report/

      - name: Upload coverage reports to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            coverage.xml
            pytest.xml
          if-no-files-found: error
